### ISSUE TITLE
Unclear instructions to setup a local copy

### ISSUE THREAD

**Issue by savnergaurav** [chirag-orbittec/graphXDemo#1]
Please include exact steps to get a running copy of the application. Thanks.

**Comment by niyatpatel23295** [comment]
+1

**Comment by chirag-orbittec** [comment]
@savnergaurav  @niyatpatel23295  Please ask your TA to spoon feed you. As I will not.
Google how to import a maven project and you will get 1000+ links with videos

**Comment by savnergaurav** [comment]
Okay thanks.
